### ISSUE TITLE
Holding values for adding a feature to send request to Slack

### ISSUE THREAD

**Issue by SteveGoodenough** [felixgborrego/gcp-pam-jit#4]
I've been looking at adding the ability to send a slack message for the request (working on a PR)  but this presents options for how to define the Slack token and channel id to a stateless app.

I could do one of the following:
1. env vars; if set then will use to attempt to send to Slack
2. config file; if defined then will use to send to Slack
3. args; have to be passed every time its called

1 is simplest, just define in your bash/zsh/etc config if required (ensure they are named to be specific to gcp-jit)
2 adds a dependency to the binary and raises a question on where to store it to be consistent for linux|mac|windows and also what format to use, yaml, toml etc?
3 just doesn't seem to user friendly but keeps the app stateless

Do you have a preference for what you'd prefer before I submit my PR?

**Comment by SteveGoodenough** [comment]
A colleague linked me to this, (so many options!) https://awesome-go.com/configuration/

but even the first option enabled config to be defined in any of my options which makes it flexible, but I'll be guided by what you may have used before and prefer.

**Comment by felixgborrego** [comment]
Hi Steve!

Thanks again for exploring the Slack integration! I was also thinking about it a while back but never got around to implementing it.

One thing to consider is creating a good developer experience here. A possible approach could be to have a separate command to configure the Slack integration, along with a basic state setup. As you already pointed out, being fully stateless is less than ideal!

For instance, the flow could be:
1) The user runs:
   `gcp-pam-jit config slack --set-token <> --channel test-channel`
2) The result is stored at `~/.config/gcp-pam-jit/config.yaml`
3) The user calls `gcp-jit request` as usual.

Also, while thinking about this, I discovered that there is already a [Slack CLI](https://api.slack.com/automation/cli/commands), which could be another option to consider. This way, users wouldn’t need to manage tokens and channels directly, and the CLI could rely on the Slack CLI instead.

Another potential approach (which could work for my internal use case) is to have a separate slack-sender-service handling communication and authentication with Slack, allowing the CLI to remain stateless.

My available time to work on this is limited, but as an idea, maybe I could add the local configuration capability for the Slack config, and you could build the Slack message sender on top of that.

@SteveGoodenough What do you think?

**Comment by SteveGoodenough** [comment]
Hi Felix,

No issue with other commitments of course, I'm just focused on it at the moment as we've recently introduced pam in the platform team (and rolling out to our service teams) and I just want it to be as painless to use as possible :grin: 

I really like the idea of `gcp-jit` creating the config as you suggested, I know we're all engineers and live by our yaml but seems nice that the app can create the config with passed values (and I don't think it needs shortcuts for those options as it's a one time thing).

I had been thinking about the fact each person would need to know the slack api key and channel id to set them up locally and had been considering using gcp secret manager but that then puts a dependency on each person having access to a project with them in (fine for us platform engineers but not our service users).

Slack CLI is an option too but does that then put a dependency on using gcp-jit that if you want slack you'll also need to install that too :thinking:

In our use case we have a dedicated (private) channel that we're using for requests (currently manually copied gcp console link) but that once approved integration uses a slack app to send an alert about the new pam access given. So my plan is to use the same slack app for the request too.

I guess for a v1 option, taking the "create config with api key and channel id and use that" is the simplest to implement so yes, if you have the time for what you suggested then I'll be more than happy to do the slack functionality :+1: 

Cheers @felixgborrego

**Comment by felixgborrego** [comment]
Hi,

Following our discussion, I implemented an initial version of the storage (it's very basic for now, but it should be enough to get the Slack integration started).

Please see my changes at: https://github.com/felixgborrego/gcp-pam-jit/pull/5
